server:
 port: 10080
mybatis:
 mapper-locations: classpath:mapper/*.xml
 type-aliases-package: com.ddb.entity
spring:
 datasource:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://192.168.43.160:3306/study-sys?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
  username: root
  password: duandaobo
 mvc:
  view:
   prefix: /pages/
   suffix: .jsp
 servlet:
  multipart:
   enabled: true
   file-size-threshold: 0
   max-file-size: 1000MB
   max-request-size: 10000MB
jodconverter:
  local:
    enabled: true
    office-home: C:\Program Files (x86)\OpenOffice 4
    max-tasks-per-process: 10
    port-numbers: 8100